modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="moreoresmod"
version="1.0.0"
displayName="MoreOresMod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Pato Salvaje, MCreator"

[[dependencies.moreoresmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




